chap03_models/chap3_project/chap3_app/urls.py
from django.conf.urls import url

from . import views
from .views import ServerList

urlpatterns = [
    url(r'^$', views.server_simple, name='server_simple'),
    url(r'^server-list/$', ServerList.as_view(), name='class_based_server_list'),
]

# v0.4
from .views import ServerPrivateList

urlpatterns += [
    url(r'^private/$', ServerPrivateList.as_view(), name='private'),
]

chap03_models/chap3_project/chap3_project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'servers/', include('chap3_app.urls', namespace='servers')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

## Added for v0.4
from django.contrib.auth import views as auth_views
urlpatterns += [
    # https://simpleisbetterthancomplex.com/tutorial/2016/06/27/how-to-use-djangos-built-in-login-system.html
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login/'}, name='logout'),
]

## Added for v0.5


from django.http import HttpResponse
from django.views.generic.base import RedirectView


urlpatterns += [
    url(r'^health/$', lambda request:HttpResponse(status=200)),
    url(r'^liveness/$', lambda request:HttpResponse(status=200)),
    url(r'^$',
        RedirectView.as_view(pattern_name='servers:server_simple', permanent=False),
                                                         name='home'),
]
# vim: ai et ts=4 sts=4 sw=4 nu ru

chap03_models/chap3_project/chap3_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# @python_2_unicode_compatible  # only if you need to support Python 2
class Server(models.Model):
    '''https://docs.djangoproject.com/en/1.11/ref/models/fields/#genericipaddressfield '''

    name = models.CharField(max_length=200, unique=True)
    ip = models.GenericIPAddressField(protocol='IPv4', unique=True)
    user = models.ForeignKey(User)

    def __str__(self):
        return '{}:{}'.format(self.name, self.ip)

# vim: ai et ts=4 sts=4 sw=4 ru nu

chap03_models/chap3_project/chap3_app/views.py
import logging

from django.conf import settings
from django.shortcuts import render
from django.views.generic import ListView

logger = logging.getLogger('verbose_logging')

from .models import Server


def server_simple(request):
    server_list = Server.objects.order_by('-ip')[:5]
    context = {'server_list': server_list}
    logger.info(server_list)
    return render(request, 'chap3_app/server_list.html', context)

class ServerList(ListView):
    model = Server


# v0.4
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

# Normally I would use https://django-braces.readthedocs.io/en/latest/index.html
# But let's use this decorator
@method_decorator(login_required, name='dispatch')
class ServerPrivateList(ListView):
    """ For tag v0.4 """
    model = Server
    template_name = 'chap3_app/private.html'

    # So how do we add extra content in this simplistic ListView
    # https://docs.djangoproject.com/en/1.11/topics/class-based-views/generic-display/#adding-extra-context

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ServerPrivateList, self).get_context_data(**kwargs)
        context['private_info'] = """You can't win, Darth. Strike me down, and I will become more powerful than you could possibly imagine."""
        return context

# vim: ai et ts=4 sts=4 sw=4 nu ru

chap03_models/chap3_project/chap3_app/templates/base.html
{% load static from staticfiles %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <meta name="description" content="django class102">
    <meta name="author" content="johnedstone">
    <link rel="icon" href="{% static 'img/favicon.ico' %}"/>

    <title>{% block head_title %}Class102{% block subtitle %}{% endblock %}{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    {% comment %}
    {# 404 error #}
    <link href="//getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    {% endcomment %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

  <!-- <nav class="navbar navbar-inverse navbar-fixed-top"> Breaking form on mobile -->
  <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand active" href="{% url 'servers:server_simple' %}">Class102</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'servers:server_simple' %}">Server Simple</a></li>
            <li><a href="{% url 'servers:class_based_server_list' %}">Class Based Views</a></li>
            <li><a href="{% url 'servers:private' %}">Private</a></li>
            {% if user.is_authenticated %}<li><a href="{% url 'logout' %}">Log out</a></li>{% endif %}
          </ul>
          {% if request.user.is_authenticated %}
          <p class="navbar-text pull-right">{{ request.user }}</p>
          {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container">
      <div class="starter-template">

    {% block page_header %}
    {% endblock page_header %}

    {% block private %}
    {% endblock private %}

    {% block content %}
    {% endblock content %}

    <hr>

    <footer class="text-muted">
        <div>
            <p>&copy; 2017 | Hogswart and Company | All rights reserved | Content for internal use only </p>
         </div>
    </footer>
    </div>
    </div> <!-- /container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="https://maxcdn.bootstrapcdn.com/js/ie10-viewport-bug-workaround.js"></script>

  </body>
</html>
{% comment %}
# vim: ai et sw=4 ts=4 sts=4 nu
{% endcomment %}

chap03_models/chap3_project/chap3_app/templates/chap3_app/private.html
{% extends 'chap3_app/server_list.html' %}

{% block subtitle %} | Private{% endblock subtitle %}

{% block private %}
    {% if private_info %}
        <h4>{{ private_info }}</h4>
    {% endif %}
{% endblock private %}

chap03_models/chap3_project/chap3_app/templates/chap3_app/server_list.html
{% extends 'base.html' %}

{% block subtitle %} Server Simple{% endblock subtitle %}



{% block content %}
<pre>

{% for ea in server_list %} 
  {{ ea.pk }} | {{ ea.name }} | {{ ea.user.username }} | {{ ea.name|upper }}
{% endfor %}

</pre>
{% endblock content %}
 

chap03_models/chap3_project/chap3_app/templates/login.html
{% extends "base.html" %}
{% load bootstrap %}
{% block subtitle %} | Sign In{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-sm-3">
            <h3>Login</h3>
            <hr>

    <form method="post" action="">
        {% csrf_token %}
        {{ form|bootstrap }}
    
    <div class="form-group">
        {# <div class="col-sm-offset-2 col-sm-10"> #}
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

    </form>

        </div>
    </div>
    
{% endblock content %}